---
# Dependencies install
- hosts: appServer
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    #- name: Add repository
    #  yum_repository:
    #    name: ius
    #    description: Hablamelo
    #    baseurl: https://centos7.iuscommunity.org/ius-release.rpm
    #- name: upgrade all packages
    #  yum:
    #    name: '*'
    #    state: latest
    - name: Install Python3
      yum:
        name:
         - epel-release
         - python36
         #- python36u 
         #- python36u-libs 
         #- python36u-devel 
         #- python36u-pip 
        state: present
